//! db.restaurants.find()
//! db.restaurants.find({cuisine:"seaFood"})
//! db.restaurants.find({halal:true})
//! db.restaurants.find({address:'India'})
//! db.restaurants.find({address:'Shinigawa'})
//! db.restaurants.find({address:[-77,564,40.677]})
//! db.restaurants.find().sort({restaurantName:1})
//! db.restaurants.find().sort({address:[1]})
//! db.restaurants.updateOne({_id:ObjectId("6395d57296499cbeae67e607")},{$set:{restaurantName:"GChocolate"}})
//! db.restaurants.updateOne({_id:ObjectId("6395d57296499cbeae67e607")},{$push:{reviews:{name:"jax",lastName:"max2",rating:4,text:"recommended",Date:13-01-2022}}})
//?db.restaurants.find().forEach(a=>printjson(`${a.restaurantName}`))
//?db.restaurants.find().forEach(a=>printjson(a.address.slice(0,1)))
//?db.restaurants.find().forEach(a=>printjson(a.address.slice(1,2)))
//! db.restaurants.updateMany({halal:false},{$set:{halal:true}})
//* db.restaurants.deleteOne({_id: ObjectId("6395d72b96499cbeae67e60a")},{$set:{restaurantName:IndianFood}})
//* db.restaurants.deleteMany({name:$exist:true})